### ISSUE TITLE
Parameter selection

### ISSUE THREAD

**Issue by flexibility2** [dragen1860/DeepEmbeddingModel_ZSL-Pytorch#1]
Hi, it's pleasure for me to read your code. However, could you explanation that in the line 83, "w1.data.normal_(0, 0.02)", why the w's std is 0.02? How you choose this parameter? And I am trying to use the "xavier_uniform", it seems that the ans is better thaner "normal_(0, 0.02)".

**Comment by dragen1860** [comment]
Hi, we select normal distribution initialization N(0, 0.02) for parameter w1 according to personal experience. You can prefer to `xavier_uniform` if it proves better.
